### PR TITLE
Fix forgotten interface declaration change

### PR DESCRIPTION
**Pull request by scott-parkhill**
I'm very sorry about this, the interface change got lost in the copy and paste from project to branch. Deepest apologies.

### CODE REVIEW

**Comment by isc30** [comment]
Hey no worries, if the build fails nothing gets really broken (it didn't publish any version or anything). Thanks a lot for the contribution!

**Comment by scott-parkhill** [comment]
Hey @isc30, do you have a time frame of when we could expect these changes in nuget? Cheers!

**Comment by scott-parkhill** [comment]
Hey @isc30, do you have a time frame of when we could expect these changes in nuget? Cheers!

**Comment by isc30** [comment]
hey, it should be already published,  will check

**Comment by scott-parkhill** [comment]
Thank you very much =)

**Pull request merged**
