### PR TITLE
Use NavigationManager instead of IUriHelper

### LINKED ISSUE #5: Update to .NETCore preview 9
Preview 9 replaced `IUriHelper` with `NavigationManager` which throws a
```
System.TypeLoadException: "Could not load type 'Microsoft.AspNetCore.Components.IUriHelper' from assembly 'Microsoft.AspNetCore.Components, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'."
```
At startup because 
`Blazor.Analytics.GoogleAnalytics.GoogleAnalyticsComponent`
is trying to load IUriHelper
Here: https://github.com/isc30/blazor-analytics/blob/7b089e70ec480a5608aa054842cc2cb39c24f2d3/src/Blazor.Analytics/GoogleAnalytics/Components/GoogleAnalyticsComponent.cs#L15

### PR DESCRIPTION
**Pull request by dedmen**
Fixes #5
Might choose a different name for the variable?

### CODE REVIEW

**Comment by isc30** [comment]
Thanks!
I'm on vacations this week so I'll mergea and create a new nuget package on Monday

**Comment by coffeelake** [comment]
Please put this through. i really want this change :)

**Comment by isc30** [comment]
Thanks for your contribution. Sorry for not reacting faster, I was on vacations 😄
The new NuGet package can be found [here](https://www.nuget.org/packages/Blazor-Analytics/1.1.0-preview9.19465.2)

**Comment by coffeelake** [comment]
can anyone verify that it works, i still get the same error unfortunately. do not know if the nuget package is updated or not or if my project is not updated. whatever i do, the error remains

**Comment by isc30** [comment]
Hi, are you using the new NuGet package version?
```cli
dotnet add package Blazor-Analytics --version 1.1.0-preview9.19465.2
```
if yes, what is the error you are facing? is it compile-time or run-time?
this release was built using the latest .NET Core SDK (3.0.100)

**Comment by coffeelake** [comment]
I just tested a brand new project and just add the package **Blazor-Analytics --version 1.1.0-preview9.19465.2** and i still get error.

TypeLoadException: Could not load type 'Microsoft.AspNetCore.Components.IUriHelper' from assembly 'Microsoft.AspNetCore.Components, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.

  @(await Html.RenderComponentAsync<App>(RenderMode.ServerPrerendered))

**Comment by isc30** [comment]
Can you create a dummy repo that I can clone to reproduce the issue? I'll
have a look ASAP

**Comment by coffeelake** [comment]
https://github.com/coffeelake/Bugs

**Comment by isc30** [comment]
Hi, it seems like your repository is missing many NuGet package references.
I just added a Demo Application using the package to the solution and it seems to work, please have a look at it.

**Comment by isc30** [comment]
Any news? @coffeelake

**Comment by coffeelake** [comment]
I downloaded the repo and changed the IUriHelper my self and got it to work. I´m gona try the nuget in the next project and see if i get same error again.

**Pull request merged**
